name: Hit Portals Daily

on:
  schedule:
    - cron: '0 */4 * * *'

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  hit-portals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      - name: Install Requests
        run: pip install requests

      - name: Run Python Script
        run: python hit_portals.py
